### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Aeropro4** [insomniachi/Totoro#25] opened 2023-05-13 15:12 UTC
After clicking on info button for any anime, it crashes after sometime.
In detail, I was searching for some anime and was viewing the info but after clicking the related tab the (Working in background cursor) appears and after few seconds totoro crashes.
Well in conclusion if i immediately start watching anime it runs smooth and there NO software for watching anime so this is a huge help

**Comment by insomniachi** [comment] 2023-05-14 05:16
1. Happens always for any anime.
2. Happens occasionally.
3. Happens always for 1 particular anime, if yes, can you tell which one.

can you tell which of the above is the issue? I can't reproduce from my side.

**Comment by Aeropro4** [comment] 2023-05-14 07:33
2. Happens occasionally.
And here's a vide for this:

https://github.com/insomniachi/Totoro/assets/113044496/966616f5-f9f2-4d95-ae47-c19c7a141089

In the end it crashes(don't mind my desktop screen cause its a mess 😅)



> 1. Happens always for any anime.
> 2. Happens occasionally.
> 3. Happens always for 1 particular anime, if yes, can you tell which one.
> 
> can you tell which of the above is the issue? I can't reproduce from my side.

**Comment by insomniachi** [comment] 2023-05-14 08:32
Should be fixed now, issue was with anime which has not yet aired.

**Comment by Aeropro4** [comment] 2023-05-15 13:03
Wow What a speed and yeah its fixed Thx really

**Closed** 2023-05-20 15:35 UTC
